
url: https://www.gragnatomarco.it

images: images
fonts: fonts

collections:
  chunks:
    output: false

defaults:
-
  scope:
    type: pages
  values:
    permalink: /:path/:basename:output_ext
-
  scope:
    type: chunks
  values:
    layout: chunk

exclude:
  - LICENSE
  - README

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
