url: "https://tgragnato.it"
title: Tommaso Gragnato

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap

exclude:
  - _site
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - vendor/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - CNAME
  - LICENSE
  - README.md

collections:
  snippets:
    output: false
