title: Gragnato Marco
email: gragnato.marco@icloud.com
telefono: 338 7085 202
github: https://github.com/tgragnato/gmarco
description: Sito Web relativo alla attività di impresa di Gragnato Marco
map: https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2798.662389723209!2d10.863930900000002!3d45.456458999999995!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4781e6a23ebcfd53%3A0x1b73b1d7ed4b91c3!2sLocalita&#39;+Ca&#39;.+di+Mezzo%2C+147%2C+37012+Bussolengo+VR!5e0!3m2!1sit!2sit!4v1429642416209
disclaimer: >
  Questo sito NON utilizza cookie.
  NON effettua profilazione dei visitatori.
url: "www.gragnatomarco.it"
exclude: ["LICENSE"]
